In [1]:
import os
import pandas as pd
import nibabel as nib
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("Data/MGMT_TCGA.csv")
df.head()

,files,labels,x,y
0,TCGA-02-0006,Unmethylated,/home/bruno-pacheco/brats-generalization/data/...,/home/bruno-pacheco/brats-generalization/data/...
1,TCGA-02-0009,Unmethylated,/home/bruno-pacheco/brats-generalization/data/...,/home/bruno-pacheco/brats-generalization/data/...
2,TCGA-02-0011,Methylated,/home/bruno-pacheco/brats-generalization/data/...,/home/bruno-pacheco/brats-generalization/data/...
3,TCGA-02-0027,Unmethylated,/home/bruno-pacheco/brats-generalization/data/...,/home/bruno-pacheco/brats-generalization/data/...
4,TCGA-02-0033,Methylated,/home/bruno-pacheco/brats-generalization/data/...,/home/bruno-pacheco/brats-generalization/data/...

In [8]:
df.shape

(76, 4)

In [10]:
df = df[["files", "labels"]]

In [11]:
df.head()

          files        labels
0  TCGA-02-0006  Unmethylated
1  TCGA-02-0009  Unmethylated
2  TCGA-02-0011    Methylated
3  TCGA-02-0027  Unmethylated
4  TCGA-02-0033    Methylated

In [16]:
files_volume_paths="/home/bruno-pacheco/brats-generalization/data/raw/TCGA/GBM/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA_GBM_radiomicFeatures.csv"
df_1 = pd.read_csv(files_volume_paths)

In [14]:
files_volume_paths="/home/bruno-pacheco/brats-generalization/data/raw/TCGA/GBM/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations_BraTS2017TestingData/TCGA_GBM_radiomicFeatures.csv"
df_2 = pd.read_csv(files_volume_paths)

In [18]:
df_3 = pd.concat([df_1, df_2]).reset_index(drop=True)

In [21]:
df_3 = df_3.merge(df, left_on="ID", right_on="files")

In [22]:
df_3.head()

,ID,Date,VOLUME_ET,VOLUME_NET,VOLUME_ED,VOLUME_TC,VOLUME_WT,VOLUME_BRAIN,VOLUME_ET_OVER_NET,VOLUME_ET_OVER_ED,...,TGM_Cog_X_5,TGM_Cog_Y_5,TGM_Cog_Z_5,TGM_T_5,TGM_Cog_X_6,TGM_Cog_Y_6,TGM_Cog_Z_6,TGM_T_6,files,labels
0,TCGA-02-0006,1996.08.23,1662,384,36268,2046,38314,1469432,4.328125,0.045826,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCGA-02-0006,Unmethylated
1,TCGA-02-0009,1997.06.14,4362,4349,15723,8711,24434,1295721,1.002989,0.277428,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCGA-02-0009,Unmethylated
2,TCGA-02-0011,1998.02.01,33404,48612,45798,82016,127814,1425843,0.687155,0.729377,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCGA-02-0011,Methylated
3,TCGA-02-0027,1999.03.28,12114,7587,34086,19701,53787,1403429,1.596679,0.355395,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCGA-02-0027,Unmethylated
4,TCGA-02-0033,1997.05.26,34538,7137,65653,41675,107328,1365237,4.839288,0.526069,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TCGA-02-0033,Methylated

In [25]:
df_3.to_csv("Data/MGMT_TCGA_FEATURES.csv", index=False)